# -*- coding: utf-8 -*-
"""Exercise_module2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUfm7haBuoLyRGEKqwPiswPNqbPXPdXg
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

"""#M**ONO IMAGE**

#12.Lightness Method:
"""

img = mpimg.imread('/content/dog.jpeg')
gray_img_03 = (img.max(axis=2) + img.min(axis=2))/2
plt.imshow(gray_img_03, cmap='gray')
plt.axis('off')  # Tắt các trục tọa độ
plt.show()
gray_img_03[0, 0]

gray_img_03


"""#13. Average Method:"""

img = mpimg.imread('/content/dog.jpeg')
gray_img_02 = img.mean(axis=2)  # Your Code Here
gray_img_02[0, 0]

plt.imshow(gray_img_02, cmap='gray')
plt.axis('off')  # Tắt các trục tọa độ
plt.show()


"""#14. Luminosity Method:"""

img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = img[:, :, 0] * 0.21 + img[:, :, 1] * \
    0.72 + img[:, :, 2] * 0.07  # Your Code Here
print(gray_img_01[0, 0])
plt.imshow(gray_img_01, cmap='gray')
plt.axis('off')  # Tắt các trục tọa độ
plt.show()
